default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: task_app_development

test:
  <<: *default
  database: task_app_test

production:
  <<: *default
  database: task_app_production
  username: task_app
  password: <%= ENV['TASK_APP_DATABASE_PASSWORD'] %>
